name: Deploy to Cloud Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Cloud Functions
        run: |
          gcloud functions deploy onUserSettingsUpdate \
            --runtime=nodejs20 \
            --region=asia-northeast1 \
            --source=./functions \
            --entry-point=onUserSettingsUpdate \
            --trigger-event providers/cloud.firestore/eventTypes/document.update \
            --trigger-resource "projects/${{ secrets.GCP_PROJECT_ID }}/databases/(default)/documents/users/{userId}/noticeSetting" \
            --timeout=120s
