name: Deploy to Cloud Functions

on:
  push:
    branches:
      - main  # mainブランチにpushされたら実行

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to Cloud Functions
        run: |
          gcloud functions deploy helloWorld \
            --gen2 \
            --runtime nodejs20 \
            --region asia-northeast1 \
            --entry-point helloWorld \
            --trigger-http \
            --allow-unauthenticated
