name: Deploy to Cloud Functions

on:
  push:
    branches:
      - main  # main ブランチに push されたときに実行

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # コード取得
      - name: Checkout code
        uses: actions/checkout@v4

      # GCP 認証
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # gcloud CLI セットアップ
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Cloud Functions にデプロイ
      - name: Deploy to Cloud Functions
        run: |
          gcloud functions deploy onUserSettingsUpdate \
            --region=asia-northeast1 \
            --runtime=nodejs20 \
            --source=./functions \
            --entry-point=onUserSettingsUpdate \
            --trigger-event google.firestore.document.update \
            --trigger-resource "projects/linebot-799ed/databases/(default)/documents/users/{userId}/noticeSetting" \
            --timeout=60s
